"""Comando `nutcracker analyze`: analiza un APK local."""

from __future__ import annotations

from pathlib import Path

import click

from nutcracker_core.config import load_config, get as cfg_get
from nutcracker_core import orchestrator as orch

from . import cli


@cli.command()
@click.argument("apk_path", type=click.Path(exists=True, dir_okay=False))
@click.option(
    "--config", "-c",
    "config_path",
    default="config.yaml",
    show_default=True,
    metavar="ARCHIVO",
)
@click.option(
    "--report", "-r",
    default=None,
    metavar="ARCHIVO",
    help="Path to save the JSON report.",
)
@click.option(
    "--launch", "-L",
    is_flag=True,
    default=False,
    help="After analysis, launch the app on device with the generated bypass script.",
)
@click.option(
    "--serial", "-s",
    default=None,
    metavar="SERIAL",
    help="ADB device serial for --launch (default: first available).",
)
@click.option(
    "--static-only",
    is_flag=True,
    default=False,
    help="Force jadx-only decompilation and skip Frida/device runtime steps "
         "(used by queued/scheduled batch runs; see `nutcracker queue`/`serve`).",
)
def analyze(apk_path: str, config_path: str, report: str | None, launch: bool, serial: str | None,
            static_only: bool) -> None:
    """Analyze a local APK for anti-root protections."""
    orch._LAUNCH_APP = launch
    orch._LAUNCH_SERIAL = serial
    config = load_config(config_path)
    if static_only:
        orch.apply_static_only_override(config)
    orch._CFG = config
    orch._init_i18n(config)
    save_json_cfg = bool(
        cfg_get(config, "features", "report_json", default=cfg_get(config, "reports", "save_json", default=False))
    )
    if not report and save_json_cfg:
        reports_dir = cfg_get(config, "reports", "output_dir") or "./reports"
        Path(reports_dir).mkdir(parents=True, exist_ok=True)
        report = str(Path(reports_dir) / f"{Path(apk_path).stem}.json")
    save_pdf = bool(
        cfg_get(config, "features", "report_pdf", default=cfg_get(config, "reports", "save_pdf", default=True))
    )

    orch._run_analysis(Path(apk_path), report, keep_apk=True, gen_pdf=save_pdf)
