"""Comando `nutcracker launch`: lanza la app con el bypass script generado."""

from __future__ import annotations

from pathlib import Path

import click

from nutcracker_core.config import load_config, get as cfg_get
from nutcracker_core.i18n import t
from nutcracker_core import orchestrator as orch
from nutcracker_core.orchestrator import console

from . import cli


@cli.command()
@click.argument("package")
@click.option(
    "--script", "-l",
    default=None,
    metavar="SCRIPT",
    help="Bypass JS script to use. If omitted, uses the latest generated for the package.",
)
@click.option(
    "--serial", "-s",
    default=None,
    metavar="SERIAL",
    help="ADB device serial (default: first available via -U).",
)
@click.option(
    "--scripts-dir",
    default="frida_scripts",
    show_default=True,
    metavar="DIR",
    help="Directory to search for bypass scripts.",
)
@click.option(
    "--config", "config_path",
    default="config.yaml",
    show_default=True,
    metavar="FILE",
    help="Config file (reads strategies.frida_host).",
)
def launch(package: str, script: str | None, serial: str | None, scripts_dir: str, config_path: str) -> None:
    """Launch the app on device with the latest generated bypass script.

    \b
    Examples:
      python nutcracker.py launch com.appexample
      python nutcracker.py launch downloads/com.appexample/com.appexample.apk
      python nutcracker.py launch com.appexample --script frida_scripts/bypass_....js
      python nutcracker.py launch com.appexample --serial emulator-5554
    """
    scripts_path = Path(scripts_dir)

    # Aceptar APK path como argumento: extraer package del nombre del archivo
    pkg = package
    p = Path(package)
    if p.suffix.lower() == ".apk" or "/" in package:
        pkg = p.stem  # e.g. "com.appexample.apk" → "com.appexample"
        console.print(f"[dim]  {t('cli_apk_detected_pkg', pkg=pkg)}[/dim]")

    if script:
        script_path = Path(script)
        if not script_path.exists():
            console.print(f"[red]Error:[/red] {t('cli_script_not_found', script=script)}")
            raise SystemExit(1)
    else:
        script_path = orch._find_latest_bypass_script(pkg, scripts_path)
        if not script_path:
            console.print(
                f"[yellow]⚠[/yellow]  {t('cli_no_bypass_found', pkg=pkg, scripts_dir=scripts_dir)}"
            )
            raise SystemExit(1)

    console.print(f"[green]✔[/green] Script: [bold]{script_path}[/bold]")
    cfg = load_config(config_path)
    frida_host = str(cfg_get(cfg, "strategies", "frida_host", default="")).strip() or None
    orch._launch_frida_bypass(pkg, script_path, serial=serial, frida_host=frida_host)
